const KEY='iulian_maria_rsvp_v2',PASS='3006';const $=s=>document.querySelector(s);let entries=[];
function load(){try{entries=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{entries=[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(entries));render()}
function openDash(){sessionStorage.setItem('im_admin','1');$('#login').hidden=true;$('#dashboard').hidden=false;load();render()}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();if($('#password').value===PASS)openDash();else $('#error').textContent='Parolă incorectă.'});if(sessionStorage.getItem('im_admin')==='1')openDash();
$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('im_admin');location.reload()};
function esc(s=''){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function render(){const q=$('#search').value.toLowerCase(),f=$('#filter').value;const filtered=entries.filter(x=>(f==='all'||x.status===f)&&(`${x.family} ${x.phone}`.toLowerCase().includes(q)));$('#rows').innerHTML=filtered.map(x=>`<tr><td><strong>${esc(x.family)}</strong></td><td><span class="badge ${x.status==='Confirmat'?'ok':x.status==='Refuzat'?'no':'wait'}">${esc(x.status)}</span></td><td>${x.adults||0}</td><td>${x.children||0}</td><td>${esc(x.phone||'—')}</td><td><input data-note="${x.id}" value="${esc(x.accommodation||'')}" placeholder="Notiță privată"></td><td><button class="row-btn" data-del="${x.id}" title="Șterge">🗑️</button></td></tr>`).join('');$('#empty').style.display=filtered.length?'none':'block';$('#confirmed').textContent=entries.filter(x=>x.status==='Confirmat').length;$('#declined').textContent=entries.filter(x=>x.status==='Refuzat').length;$('#pending').textContent=entries.filter(x=>x.status==='În așteptare').length;$('#adults').textContent=entries.filter(x=>x.status==='Confirmat').reduce((a,x)=>a+(x.adults||0),0);$('#children').textContent=entries.filter(x=>x.status==='Confirmat').reduce((a,x)=>a+(x.children||0),0);document.querySelectorAll('[data-note]').forEach(i=>i.onchange=()=>{const x=entries.find(e=>e.id===i.dataset.note);if(x){x.accommodation=i.value;save()}});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Ștergi această înregistrare?')){entries=entries.filter(x=>x.id!==b.dataset.del);save()}})}
$('#search').oninput=render;$('#filter').onchange=render;$('#addPending').onclick=()=>{const family=prompt('Numele familiei:');if(!family)return;entries.push({id:Date.now().toString(),family,status:'În așteptare',adults:0,children:0,phone:'',accommodation:'',createdAt:new Date().toISOString()});save()};
$('#exportBtn').onclick=()=>{const rows=[['Familie','Status','Adulti','Copii','Telefon','Notite cazare','Data'],...entries.map(x=>[x.family,x.status,x.adults,x.children,x.phone,x.accommodation,new Date(x.createdAt).toLocaleString('ro-RO')])];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='confirmari_iulian_maria.csv';a.click();URL.revokeObjectURL(a.href)};
