const $=(s)=>document.querySelector(s), $$=(s)=>document.querySelectorAll(s);
window.addEventListener('load',()=>setTimeout(()=>$('#loader').classList.add('hide'),350));
window.addEventListener('scroll',()=>$('.site-header').classList.toggle('scrolled',scrollY>40));
$('#menuBtn').addEventListener('click',()=>{const n=$('#nav');n.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',n.classList.contains('open'))});
$$('#nav a').forEach(a=>a.addEventListener('click',()=>$('#nav').classList.remove('open')));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
function tick(){const target=new Date('2026-11-07T14:00:00+02:00').getTime(),d=Math.max(0,target-Date.now());$('#days').textContent=String(Math.floor(d/86400000)).padStart(3,'0');$('#hours').textContent=String(Math.floor(d/3600000)%24).padStart(2,'0');$('#minutes').textContent=String(Math.floor(d/60000)%60).padStart(2,'0');$('#seconds').textContent=String(Math.floor(d/1000)%60).padStart(2,'0')}tick();setInterval(tick,1000);
const KEY='iulian_maria_rsvp_v2';
function getEntries(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
$('#rsvpForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);const entry={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(),family:fd.get('family').trim(),status:fd.get('status'),adults:Number(fd.get('adults')),children:Number(fd.get('children')),phone:fd.get('phone').trim(),createdAt:new Date().toISOString(),accommodation:''};const list=getEntries();list.push(entry);localStorage.setItem(KEY,JSON.stringify(list));$('#successText').textContent=entry.status==='Confirmat'?`Dragă ${entry.family}, confirmarea voastră a fost înregistrată. Abia așteptăm să sărbătorim împreună!`:`Dragă ${entry.family}, vă mulțumim că ne-ați răspuns. Ne pare rău că nu puteți fi alături de noi.`;$('#successModal').classList.add('open');$('#successModal').setAttribute('aria-hidden','false');e.target.reset()});
function closeModal(){$('#successModal').classList.remove('open');$('#successModal').setAttribute('aria-hidden','true')}$('#closeModal').addEventListener('click',closeModal);$('#successModal').addEventListener('click',e=>{if(e.target.id==='successModal')closeModal()});
